// AUTO-GENERATED by Aiden HX — in-browser mock API seeded from Jira stories.
// Patches window.fetch so /api/* routes resolve against in-memory stores.
// Do not edit manually; regenerate by re-running the pipeline.

type Record = { id: string; [k: string]: any };
type Store = Record[];

const LATENCY_MS = 60;
const RESOURCES: string[] = ["dashboard-load", "each-query", "page-username"];
const SEED: Record<string, Store> = {
  "dashboard-load": [
    {
      "id": "dashboard-load-1",
      "name": "Sample Dashboard-Load 1",
      "status": "active",
      "createdAt": "2026-04-10T10:00:00Z"
    },
    {
      "id": "dashboard-load-2",
      "name": "Sample Dashboard-Load 2",
      "status": "pending",
      "createdAt": "2026-04-11T10:00:00Z"
    },
    {
      "id": "dashboard-load-3",
      "name": "Sample Dashboard-Load 3",
      "status": "completed",
      "createdAt": "2026-04-12T10:00:00Z"
    }
  ],
  "each-query": [
    {
      "id": "each-query-1",
      "name": "Sample Each-Query 1",
      "status": "active",
      "createdAt": "2026-04-10T10:00:00Z"
    },
    {
      "id": "each-query-2",
      "name": "Sample Each-Query 2",
      "status": "pending",
      "createdAt": "2026-04-11T10:00:00Z"
    },
    {
      "id": "each-query-3",
      "name": "Sample Each-Query 3",
      "status": "completed",
      "createdAt": "2026-04-12T10:00:00Z"
    }
  ],
  "page-username": [
    {
      "id": "page-username-1",
      "name": "Sample Page-Username 1",
      "status": "active",
      "createdAt": "2026-04-10T10:00:00Z"
    },
    {
      "id": "page-username-2",
      "name": "Sample Page-Username 2",
      "status": "pending",
      "createdAt": "2026-04-11T10:00:00Z"
    },
    {
      "id": "page-username-3",
      "name": "Sample Page-Username 3",
      "status": "completed",
      "createdAt": "2026-04-12T10:00:00Z"
    }
  ]
} as any;

const stores: Record<string, Store> = {};
for (const r of RESOURCES) {
  stores[r] = Array.isArray(SEED[r]) ? [...SEED[r]] : [];
}

const sleep = (ms: number) => new Promise(res => setTimeout(res, ms));

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json' },
  });
}

function parseApiPath(pathname: string): { resource: string; id?: string } | null {
  const m = pathname.match(/^\/api\/([^/?#]+)(?:\/([^/?#]+))?/);
  if (!m) return null;
  return { resource: decodeURIComponent(m[1]), id: m[2] ? decodeURIComponent(m[2]) : undefined };
}

async function handle(req: Request): Promise<Response> {
  const url = new URL(req.url, window.location.origin);
  const parsed = parseApiPath(url.pathname);
  if (!parsed) return jsonResponse({ error: 'Not found' }, 404);
  const { resource, id } = parsed;
  if (!stores[resource]) stores[resource] = [];
  const store = stores[resource];
  const method = req.method.toUpperCase();

  await sleep(LATENCY_MS);

  try {
    if (method === 'GET') {
      if (id) {
        const rec = store.find(r => String(r.id) === id);
        return rec ? jsonResponse(rec) : jsonResponse({ error: 'Not found' }, 404);
      }
      return jsonResponse(store);
    }
    if (method === 'POST') {
      const body = await req.json().catch(() => ({}));
      const rec: Record = {
        id: (crypto as any).randomUUID ? (crypto as any).randomUUID() : String(Date.now()),
        createdAt: new Date().toISOString(),
        ...body,
      };
      store.push(rec);
      return jsonResponse(rec, 201);
    }
    if (method === 'PUT' && id) {
      const body = await req.json().catch(() => ({}));
      const idx = store.findIndex(r => String(r.id) === id);
      if (idx === -1) return jsonResponse({ error: 'Not found' }, 404);
      store[idx] = { ...body, id };
      return jsonResponse(store[idx]);
    }
    if (method === 'PATCH' && id) {
      const body = await req.json().catch(() => ({}));
      const idx = store.findIndex(r => String(r.id) === id);
      if (idx === -1) return jsonResponse({ error: 'Not found' }, 404);
      store[idx] = { ...store[idx], ...body, id };
      return jsonResponse(store[idx]);
    }
    if (method === 'DELETE' && id) {
      const idx = store.findIndex(r => String(r.id) === id);
      if (idx === -1) return jsonResponse({ error: 'Not found' }, 404);
      const [removed] = store.splice(idx, 1);
      return jsonResponse(removed);
    }
    return jsonResponse({ error: `Method ${method} not supported` }, 405);
  } catch (e: any) {
    return jsonResponse({ error: e?.message || 'Internal error' }, 500);
  }
}

const originalFetch = window.fetch.bind(window);
window.fetch = async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
  try {
    const url = typeof input === 'string' ? input : (input as Request).url ?? String(input);
    if (url.includes('/api/')) {
      const req = input instanceof Request ? input : new Request(url, init);
      return await handle(req);
    }
  } catch {
    // Fall through to real fetch
  }
  return originalFetch(input as any, init);
};

export {};
